### ISSUE TITLE
failed to start on centos 6.5

### ISSUE THREAD

**Issue by rsb** [rsb/rsb-gol#1]
/home/rscott/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsb-gol-0.4.1/lib/rsb/gol/cli.rb:53:in `ioctl': Invalid argument (Errno::EINVAL)
	from /home/rscott/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsb-gol-0.4.1/lib/rsb/gol/cli.rb:53:in `screen_size'
	from /home/rscott/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsb-gol-0.4.1/lib/rsb/gol/cli.rb:14:in `start'
	from /home/rscott/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/rscott/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/rscott/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/rscott/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/rscott/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsb-gol-0.4.1/exe/gol:5:in `<top (required)>'
	from /home/rscott/.rbenv/versions/2.2.2/bin/gol:23:in `load'
	from /home/rscott/.rbenv/versions/2.2.2/bin/gol:23:in `<main>'

**Comment by rsb** [comment]
replaced terminal size code with highline gem
